ek

diff --git a/.pipelines/jenkins/apps/pars/Jenkinsfile-dev b/.pipelines/jenkins/apps/pars/Jenkinsfile-dev
--- a/.pipelines/jenkins/apps/pars/Jenkinsfile-dev
+++ b/.pipelines/jenkins/apps/pars/Jenkinsfile-dev
@@ -141,7 +141,7 @@ pipeline {
                 axes {
                     axis {
                         name 'ARCH'
-                        values 'x86_64', 'arm64'
+                        values 'x86_64'
                     }
                 }
                 stages {
@@ -317,11 +317,194 @@ pipeline {
             }
         }
 
+        stage('Build Linux Matrix (Rhel)') {
+            matrix {
+                axes {
+                    axis {
+                        name 'ARCH'
+                        values 'arm64'
+                    }
+                }
+                stages {
+                    stage("Build Binary") {
+                        agent { label 'linux' } 
+                        steps {
+                            script {
+
+                                def OS = "linux"
+                                def versionOutput = readFile("${WORKSPACE}/version_output.txt")
+                                def buildVersion = versionOutput.split('\n').find { it.startsWith('BUILD_VERSION=') }?.split('=')[1]?.trim()
+                                def extLine = versionOutput.split('\n').find { it.startsWith('EXT=') }
+                                def ext = (extLine?.contains('=') && extLine.split('=').length > 1) ? extLine.split('=')[1].trim() : ""
+
+                                // Make komutunu çalıştırarak binary dosyasını oluşturuyoruz
+                                sh """
+                                    make build.binary.${OS}.${ARCH} VERSION=$buildVersion
+                                """
+
+                                // Binary dosyasının çıkış yolunu belirliyoruz
+                                def binaryOutputPathBase = "dist/${buildVersion}/${OS}/bin/${ARCH}"
+                                def binaryOutputPath = "${binaryOutputPathBase}/pars${ext}"
+                                def binaryChecksumPath = "${binaryOutputPathBase}/checksum.txt"
+
+                                // Binary dosyasının checksum'unu hesaplıyoruz
+                                def binaryChecksum = sh(script: "sha256sum ${binaryOutputPath} | awk '{print \$1}'", returnStdout: true).trim()
+
+                                // Checksum değerini ekrana yazdırıyoruz
+                                echo "Checksum for ${binaryOutputPath}: ${binaryChecksum}"
+
+                                // Checksum ve dosya yolunu checksums.txt dosyasına yazıyoruz
+                                sh """
+                                    echo "${binaryChecksum}" > ${binaryChecksumPath}
+                                """
+                                
+
+                                // // Binary dosyasının yolunu environment değişkeni olarak ekliyoruz
+                                // env.BINARY_OUTPUT_PATH_BASE = binaryOutputPathBase
+                                // env.BINARY_OUTPUT_PATH = binaryOutputPath
+                                // env.BINARY_CHECKSUM_PATH = binaryChecksumPath
+
+                                // // Environment değişkenlerini GitHub Actions ortamına aktarıyoruz (isteğe bağlı)
+                                // echo "BINARY_OUTPUT_PATH_BASE=\${binaryOutputPathBase}" >> $GITHUB_ENV
+                                // echo "BINARY_OUTPUT_PATH=\${binaryOutputPath}" >> $GITHUB_ENV
+                                // echo "BINARY_CHECKSUM_PATH=\${binaryChecksumPath}" >> $GITHUB_ENV
+                            }
+                        }
+                    }
+                    stage('Prepare Artifact and Checksum') {
+                        agent { label 'linux' } 
+                        steps {
+                            script {
+                                def OS = "linux"
+                                def versionOutput = readFile("${WORKSPACE}/version_output.txt")
+                                def appName = versionOutput.split('\n').find { it.startsWith('APPNAME=') }?.split('=')[1]?.trim()
+                                def buildVersion = versionOutput.split('\n').find { it.startsWith('BUILD_VERSION=') }?.split('=')[1]?.trim()
+                                def extLine = versionOutput.split('\n').find { it.startsWith('EXT=') }
+                                def ext = (extLine?.contains('=') && extLine.split('=').length > 1) ? extLine.split('=')[1].trim() : ""
+
+                                def originalFileName = "${appName}${ext}"
+                                def newBaseName = "${appName}-${OS}-${ARCH}${ext}"
+
+                                def binaryOutputPathBase = "${WORKSPACE}/dist/${buildVersion}/${OS}/bin/${ARCH}"
+                                def binaryOutputPath = "${binaryOutputPathBase}/pars${ext}"
+                                def binaryChecksumPath = "${binaryOutputPathBase}/checksum.txt"
+                                
+                                def artifactPath = "dist/artifacts/${buildVersion}"
+
+                                // Hedef klasör oluşturulmadıysa oluştur
+                                sh "mkdir -p ${artifactPath}"
+
+                                // Dosyayı kopyala
+                                sh "cp ${binaryOutputPathBase}/${originalFileName} ${artifactPath}/${newBaseName}"
+
+                                // Checksum oku
+                                def binaryChecksum = readFile("${binaryChecksumPath}").trim()
+
+                                // Checksums.md'ye yaz
+                                def type = "Binary"
+                                def line = "| ${OS} | ${ARCH} | ${type} | ${newBaseName} | ${binaryChecksum} |"
+                                sh "echo '${line}' >> ${artifactPath}/Checksums.md"
+
+
+
+                                stash includes: 'dist/artifacts/**/*', name: 'linux-debian-artifacts'
+                            }
+                        }
+                    }
+                    stage('Archive and Generate Metadata') {
+                        agent { label 'linux' } // İstediğiniz agent etiketini kullanın
+                        steps {
+                            script {
+                                def MATRIX_ARCHIVE = 'tar.gz'   // zip, tar.gz, 7z, rar destekleniyor
+                                def OS = "linux"
+                                def versionOutput = readFile("${WORKSPACE}/version_output.txt")
+                                def appName = versionOutput.split('\n').find { it.startsWith('APPNAME=') }?.split('=')[1]?.trim()
+                                def buildVersion = versionOutput.split('\n').find { it.startsWith('BUILD_VERSION=') }?.split('=')[1]?.trim()
+                                def html_output_dir = versionOutput.split('\n').find { it.startsWith('HTML_OUTPUT_DIR=') }?.split('=')[1]?.trim()
+                                def extLine = versionOutput.split('\n').find { it.startsWith('EXT=') }
+                                def ext = (extLine?.contains('=') && extLine.split('=').length > 1) ? extLine.split('=')[1].trim() : ""
+
+
+                                def binaryOutputPathBase = "${WORKSPACE}/dist/${buildVersion}/${OS}/bin/${ARCH}"
+                                def binaryOutputPath = "${binaryOutputPathBase}/pars${ext}"
+                                def binaryChecksumPath = "${binaryOutputPathBase}/checksum.txt"
+                                
+                                def artifactPath = "dist/artifacts/${buildVersion}"
+
+                                if (fileExists(binaryOutputPathBase) && fileExists(binaryChecksumPath)) {
+                                    echo "Binary and Checksum files are present."
+                                } else {
+                                    echo "Required files do not exist. Skipping archive step."
+                                    return
+                                }
+
+                                def newBaseName = "${appName}-${OS}-${ARCH}.bin.${MATRIX_ARCHIVE}"
+                                def binaryTempPath = "${WORKSPACE}/dist/temp/${buildVersion}/${appName}-${OS}-${ARCH}-${MATRIX_ARCHIVE}"
+
+                                sh """
+                                    mkdir -p ${binaryTempPath}/bin
+                                    cp -r ${binaryOutputPathBase} ${binaryTempPath}/bin/
+
+                                    mkdir -p ${binaryTempPath}/meta
+                                    cp -r ${binaryChecksumPath} ${binaryTempPath}/meta/
+
+                                    mkdir -p ${binaryTempPath}/docs
+                                    cp -r ${html_output_dir}/ ${binaryTempPath}/docs/
+                                """
+
+                                if (MATRIX_ARCHIVE == "zip") {
+                                    sh "cd ${binaryTempPath} && zip -r '${newBaseName}' ."
+                                } else if (MATRIX_ARCHIVE == "tar.gz") {
+                                    sh """
+                                        cd ${binaryTempPath} && tar -czf '${newBaseName}' . --warning=no-file-changed || true
+                                        if ! tar -tzf '${binaryTempPath}/${newBaseName}' > /dev/null; then
+                                            echo "Error: Cannot list contents of archive."
+                                        fi
+                                    """
+                                } else if (MATRIX_ARCHIVE == "7z") {
+                                    sh "cd ${binaryTempPath} && 7z a '${newBaseName}' *"
+                                } else if (MATRIX_ARCHIVE == "rar") {
+                                    sh "cd ${binaryTempPath} && rar a '${newBaseName}' *"
+                                }
+
+                                sh "cp '${binaryTempPath}/${newBaseName}' '${artifactPath}/${newBaseName}'"
+
+                                def archiveChecksum = sh(script: "sha256sum '${binaryTempPath}/${newBaseName}' | awk '{print \$1}'", returnStdout: true).trim()
+
+                                echo "Checksum for ${binaryTempPath}/${newBaseName}: ${archiveChecksum}"
+
+                                def type = "Archive"
+                                def line = "| ${OS} | ${ARCH} | ${type} | ${newBaseName} | ${archiveChecksum} |"
+                                sh "echo '${line}' >> ${artifactPath}/Checksums.md"
+
+
+                                stash includes: 'dist/artifacts/**/*', name: 'linux-debian-archive-artifacts'
+
+                            }
+                        }
+                    }
+
+                    stage("Build RPM Package") {
+                        agent { label 'rhel' } 
+                        steps {
+                            script {
+
+                                echo ">>> rpm package generated <<<"
+                            }
+                        }
+                    }
+
+                }
+            }
+        }
+
         stage('Collect Artifacts') {
             agent { label 'linux' }
             steps {
                 unstash 'linux-rhel-artifacts'
                 unstash 'linux-rhel-archive-artifacts'
+                unstash 'linux-debian-artifacts'
+                unstash 'linux-debian-archive-artifacts'
                 archiveArtifacts artifacts: 'dist/artifacts/**/*', fingerprint: true
 
                 sh 'rm -rf dist/*'
