ek

diff --git a/.github/workflows/build-dev-matrix.yml b/.github/workflows/build-dev-matrix.yml
--- a/.github/workflows/build-dev-matrix.yml
+++ b/.github/workflows/build-dev-matrix.yml
@@ -10,10 +10,6 @@ jobs:
   prepare:
     runs-on: ubuntu-latest
 
-    container:
-      image: ahmetsoner/gh-build-image:latest
-      options: --user builder
-
     outputs:
       version: ${{ steps.version_and_tag.outputs.version }}
       base_version: ${{ steps.version_and_tag.outputs.base_version }}
@@ -27,99 +23,58 @@ jobs:
         with:
           fetch-depth: 0
 
-      - name: Prepare version and tag
+      - name: Prepare Version and Tag
         id: version_and_tag
-        run: |
-
-          git config --global user.email "you@example.com"
-          git config --global user.name "Your Name"
-
-
-
-          CHANNEL=dev
-
-          CURRENT_BASE_VERSION=$(grm flow phase dev --next --print=base)
-          TAG_NAME=${GITHUB_REF#refs/tags/}
-          BUILD_VERSION=$TAG_NAME
-
-          git checkout dev
-
-          make build.cmake.$BUILD_VERSION
-
-          mkdir -p CHANGELOG
-          echo "VERSION=$BUILD_VERSION" >> $GITHUB_ENV
-          echo "BASE_VERSION=$CURRENT_BASE_VERSION" >> $GITHUB_ENV
-          echo "CHANGELOG_PATH=CHANGELOG/$BUILD_VERSION.md" >> $GITHUB_ENV
-
-
-          # Correctly append outputs to the GITHUB_OUTPUT
-          echo "version=$BUILD_VERSION" >> $GITHUB_OUTPUT
-          echo "base_version=$CURRENT_BASE_VERSION" >> $GITHUB_OUTPUT
-          echo "changelog_path=CHANGELOG/$BUILD_VERSION.md" >> $GITHUB_OUTPUT
+        uses: ./.github/actions/prepare-version
+        with:
+          channel: "dev"
+          branch: "dev"
+          email: "you@example.com"
+          name: "Your Name"
 
       - name: Prepare artifact
         id: artifact
-        run: |
-
-          ARTIFACT_PATH=dist/artifacts/$VERSION
-          mkdir -p $ARTIFACT_PATH
-
-
-          echo "ARTIFACT_PATH=$ARTIFACT_PATH" >> $GITHUB_ENV
-          echo "artifact_path=$ARTIFACT_PATH" >> $GITHUB_OUTPUT
+        uses: ./.github/actions/prepare-artifact
+        with:
+          version: ${{ steps.version_and_tag.outputs.version }}
 
       - name: Convert Markdown Docs to HTML Docs
         id: docs
-        run: |
-
-          # Define the base directory for your HTML output
-          HTML_OUTPUT_DIR="temp/$VERSION/html_docs"
-
-          # Ensure the base output directory exists
-          mkdir -p "$HTML_OUTPUT_DIR"
-          cp -r docs/assets/ $HTML_OUTPUT_DIR
-
-          # Find all Markdown files and convert them to HTML
-          find ./docs -name '*.md' | while read -r FILE; do
-            # Get the relative path, stripping the leading ./docs/
-            RELATIVE_PATH="${FILE#./docs/}"
-            
-            # Change the extension from .md to .html
-            HTML_FILE="${RELATIVE_PATH%.md}.html"
-
-            # Create the directory structure in the output directory
-            mkdir -p "$HTML_OUTPUT_DIR/$(dirname "$RELATIVE_PATH")"
-
-            # Convert the Markdown file to HTML in the correct directory
-            pandoc --standalone --css="../assets/style/style.css" -o "$HTML_OUTPUT_DIR/$HTML_FILE" --lua-filter=scripts/change_links.lua "$FILE"
-          done
-
-          echo "HTML_OUTPUT_DIR=$HTML_OUTPUT_DIR" >> $GITHUB_ENV
-          echo "html_output_dir=$HTML_OUTPUT_DIR" >> $GITHUB_OUTPUT
+        uses: ./.github/actions/crete-html-docs
+        with:
+          version: ${{ steps.version_and_tag.outputs.version }}
 
       - name: Generate release notes
         run: |
-
+          VERSION=${{ steps.version_and_tag.outputs.version }}
+          BASE_VERSION=${{ steps.version_and_tag.outputs.base_version }}
+          CHANGELOG_PATH=${{ steps.version_and_tag.outputs.changelog_path }}
           grm changelog generate --from $BASE_VERSION-dev.1 --to $VERSION --environment dev --output $CHANGELOG_PATH
 
       - name: Create markdown file for checksums
         run: |
-
           echo "| Platform | Architecture | Type      | File Name | SHA-256 Checksum |" > $ARTIFACT_PATH/Checksums.md
           echo "|----------|--------------|-----------|-----------|------------------|" >> $ARTIFACT_PATH/Checksums.md
+          echo "-------"
+          echo $ARTIFACT_PATH
+          ls -la $ARTIFACT_PATH
+          echo "-------"
 
   build-matrix:
     runs-on: ubuntu-latest
     needs: prepare
 
-    container:
-      image: ahmetsoner/gh-build-image:latest
-      options: --user builder
-
     strategy:
       max-parallel: 1
       matrix:
         include:
+          - os: linux
+            arch: x86_64
+            targets: ["binary"]
+            binary: true
+            archive: tar.gz
+            # deb: true
+            # rpm: true
           # - os: windows
           #   arch: x86_64
           #   binary: true
@@ -132,11 +87,6 @@ jobs:
           #   arch: arm64
           #   binary: true
           #   archive: zip
-          - os: linux
-            arch: x86_64
-            binary: true
-            # archive: tar.gz
-            deb: true
           # - os: linux
           #   arch: arm64
           #   binary: true
@@ -191,6 +141,7 @@ jobs:
         # make build.binary.linux.arm64 gibi işlemlerin output pathini gösteren bir komut daha olmalı
         run: |
 
+          VERSION=${{ needs.prepare.outputs.version }}
           make build.binary.${{matrix.os}}.${{matrix.arch}} VERSION=$VERSION
 
           BINARY_OUTPUT_PATH_BASE=dist/$VERSION/${{matrix.os}}/bin/${{matrix.arch}}
@@ -218,6 +169,10 @@ jobs:
           ORIGINAL_FILE_NAME="$APPNAME$EXT"
 
           # Copy the file to its new location with the new name
+          echo "-------"
+          echo $ARTIFACT_PATH
+          ls -la $ARTIFACT_PATH
+          echo "-------"
           cp "$BINARY_OUTPUT_PATH_BASE/$ORIGINAL_FILE_NAME" "$ARTIFACT_PATH/$NEW_BASE_NAME"
 
           CHECKSUM=$(cat "$BINARY_OUTPUT_PATH_BASE/checksum.txt")
@@ -229,75 +184,98 @@ jobs:
           # Add entry to Checksums.md
           echo "| $OS | $ARCH | $TYPE | $FILENAME | $CHECKSUM |" >> "$ARTIFACT_PATH/Checksums.md"
 
-      - name: Create Artifact Archive
-        if: ${{ matrix.binary && matrix.archive }}
-        run: |
+      # - name: Create Artifact Archive
+      #   if: ${{ matrix.binary && matrix.archive }}
+      #   run: |
+      #     VERSION=${{ needs.prepare.outputs.version }}
 
-          # # Daha sonra burda file check yapılarak matrix.binary'den bağımsız ilerletilebilir olması sağlanacak
-          # if [ -f "$BINARY_OUTPUT_PATH" ] && [ -f "$BINARY_CHECKSUM_PATH" ]; then
-          #     echo "Bin and Checksum files are present at specified paths."
-          # else
-          #     echo "Required files do not exist. Skipping archive step."
-          # fi
+      #     # Daha sonra burda file check yapılarak matrix.binary'den bağımsız ilerletilebilir olması sağlanacak
+      #     if [ -f "$BINARY_OUTPUT_PATH" ] && [ -f "$BINARY_CHECKSUM_PATH" ]; then
+      #         echo "Bin and Checksum files are present at specified paths."
+      #     else
+      #         echo "Required files do not exist. Skipping archive step."
+      #     fi
 
-          # NEW_BASE_NAME=$APPNAME-${{matrix.os}}-${{matrix.arch}}.bin.${{ matrix.archive }}
-          # BINARY_TEMP_PATH=dist/temp/$VERSION/$APPNAME-${{matrix.os}}-${{matrix.arch}}-${{ matrix.archive }}
+      #     NEW_BASE_NAME=$APPNAME-${{matrix.os}}-${{matrix.arch}}.bin.${{ matrix.archive }}
+      #     BINARY_TEMP_PATH=dist/temp/$VERSION/$APPNAME-${{matrix.os}}-${{matrix.arch}}-${{ matrix.archive }}
 
-          # mkdir -p $BINARY_TEMP_PATH/bin
-          # cp $BINARY_OUTPUT_PATH "$BINARY_TEMP_PATH/bin/"
+      #     mkdir -p $BINARY_TEMP_PATH/bin
+      #     cp $BINARY_OUTPUT_PATH "$BINARY_TEMP_PATH/bin/"
 
-          # mkdir -p $BINARY_TEMP_PATH/meta
-          # cp $BINARY_OUTPUT_PATH_BASE/checksum.txt "$BINARY_TEMP_PATH/meta/checksum.txt"
+      #     mkdir -p $BINARY_TEMP_PATH/meta
+      #     cp $BINARY_OUTPUT_PATH_BASE/checksum.txt "$BINARY_TEMP_PATH/meta/checksum.txt"
 
-          # # Copy docs into the temp directory hierarchically
-          # mkdir -p $BINARY_TEMP_PATH/docs
-          # cp -r $HTML_OUTPUT_DIR/ $BINARY_TEMP_PATH/docs/
+      #     # Copy docs into the temp directory hierarchically
+      #     mkdir -p $BINARY_TEMP_PATH/docs
+      #     cp -r $HTML_OUTPUT_DIR/ $BINARY_TEMP_PATH/docs/
 
-          # if [ "${{ matrix.archive }}" = "zip" ]; then
-          #   (cd $BINARY_TEMP_PATH && zip -r "$NEW_BASE_NAME" .)
-          # elif [ "${{ matrix.archive }}" = "tar.gz" ]; then
-          #   (cd $BINARY_TEMP_PATH && tar -czf "$NEW_BASE_NAME" . --warning=no-file-changed || true )
-          #   if ! tar -tzf "$BINARY_TEMP_PATH/$NEW_BASE_NAME" > /dev/null; then
-          #     echo "Error with archive: Unable to list contents for validation."
-          #   fi
-          # elif [ "${{ matrix.archive }}" = "7z" ]; then
-          #   (cd $BINARY_TEMP_PATH && 7z a "$NEW_BASE_NAME" *)
-          # elif [ "${{ matrix.archive }}" = "rar" ]; then
-          #   ( cd $BINARY_TEMP_PATH && rar a $NEW_BASE_NAME * )
-          # fi
+      #     if [ "${{ matrix.archive }}" = "zip" ]; then
+      #       (cd $BINARY_TEMP_PATH && zip -r "$NEW_BASE_NAME" .)
+      #     elif [ "${{ matrix.archive }}" = "tar.gz" ]; then
+      #       (cd $BINARY_TEMP_PATH && tar -czf "$NEW_BASE_NAME" . --warning=no-file-changed || true )
+      #       if ! tar -tzf "$BINARY_TEMP_PATH/$NEW_BASE_NAME" > /dev/null; then
+      #         echo "Error with archive: Unable to list contents for validation."
+      #       fi
+      #     elif [ "${{ matrix.archive }}" = "7z" ]; then
+      #       (cd $BINARY_TEMP_PATH && 7z a "$NEW_BASE_NAME" *)
+      #     elif [ "${{ matrix.archive }}" = "rar" ]; then
+      #       ( cd $BINARY_TEMP_PATH && rar a $NEW_BASE_NAME * )
+      #     fi
 
-          # cp "$BINARY_TEMP_PATH/$NEW_BASE_NAME" "$ARTIFACT_PATH/$NEW_BASE_NAME"
+      #     cp "$BINARY_TEMP_PATH/$NEW_BASE_NAME" "$ARTIFACT_PATH/$NEW_BASE_NAME"
 
-          # # Calculate the checksum and store it in a variable
-          # BINARY_PACKAGE_CHECKSUM=$(sha256sum "$BINARY_TEMP_PATH/$NEW_BASE_NAME" | awk '{print $1}')
+      #     # Calculate the checksum and store it in a variable
+      #     BINARY_PACKAGE_CHECKSUM=$(sha256sum "$BINARY_TEMP_PATH/$NEW_BASE_NAME" | awk '{print $1}')
 
-          # # Append the checksum and filepath to checksums.txt
-          # echo "$BINARY_PACKAGE_CHECKSUM" > $BINARY_TEMP_PATH/checksum.txt
+      #     # Append the checksum and filepath to checksums.txt
+      #     echo "$BINARY_PACKAGE_CHECKSUM" > $BINARY_TEMP_PATH/checksum.txt
 
-          # CHECKSUM=$(cat $BINARY_TEMP_PATH/checksum.txt)
-          # OS=${{matrix.os}}
-          # ARCH=${{matrix.arch}}
-          # TYPE=Archieve
-          # FILENAME=$NEW_BASE_NAME
+      #     CHECKSUM=$(cat $BINARY_TEMP_PATH/checksum.txt)
+      #     OS=${{matrix.os}}
+      #     ARCH=${{matrix.arch}}
+      #     TYPE=Archieve
+      #     FILENAME=$NEW_BASE_NAME
 
-          # echo "| $OS | $ARCH | $TYPE | $FILENAME | $CHECKSUM |" >> $ARTIFACT_PATH/Checksums.md
+      #     echo "| $OS | $ARCH | $TYPE | $FILENAME | $CHECKSUM |" >> $ARTIFACT_PATH/Checksums.md
 
-      - name: Build Package
-        if: ${{ matrix.os == 'linux' && matrix.deb }}
-        run: |
+      # - name: Build .deb Package
+      #   if: ${{ matrix.os == 'linux' && matrix.deb }}
+      #   run: |
 
-          PCKG_PATH=usr/bin/pars
+      #     VERSION=${{ needs.prepare.outputs.version }}
+      #     PCKG_PATH=usr/bin/pars
 
-          PACKAGE_OUTPUT_PATH_BASE=dist/$VERSION/${{matrix.os}}/pkg/deb/${{matrix.arch}}/$APPNAME
-          PACKAGE_BINARY_OUTPUT_PATH=$PACKAGE_OUTPUT_PATH_BASE/$PCKG_PATH
+      #     PACKAGE_OUTPUT_PATH_BASE=dist/$VERSION/${{matrix.os}}/pkg/deb/${{matrix.arch}}/$APPNAME
+      #     PACKAGE_BINARY_OUTPUT_PATH=$PACKAGE_OUTPUT_PATH_BASE/$PCKG_PATH
 
-          mkdir -p $PACKAGE_BINARY_OUTPUT_PATH
+      #     mkdir -p $PACKAGE_BINARY_OUTPUT_PATH
 
-          NEW_BASE_NAME=$APPNAME-${{matrix.os}}-${{matrix.arch}}$EXT
-          ORIGINAL_FILE_NAME="$APPNAME$EXT"
+      #     NEW_BASE_NAME=$APPNAME-${{matrix.os}}-${{matrix.arch}}$EXT
+      #     ORIGINAL_FILE_NAME="$APPNAME$EXT"
 
-          cp "$BINARY_OUTPUT_PATH_BASE/$ORIGINAL_FILE_NAME" "$PACKAGE_BINARY_OUTPUT_PATH"
+      #     cp "$BINARY_OUTPUT_PATH_BASE/$ORIGINAL_FILE_NAME" "$PACKAGE_BINARY_OUTPUT_PATH"
 
-          make build.deb.package.${{matrix.arch}}.configuration VERSION=$VERSION
-          make build.deb.package.${{matrix.arch}}.payload VERSION=$VERSION
-          make build.deb.package.${{matrix.arch}}.package VERSION=$VERSION
+      #     make build.deb.package.${{matrix.arch}}.configuration VERSION=$VERSION
+      #     make build.deb.package.${{matrix.arch}}.payload VERSION=$VERSION
+      #     make build.deb.package.${{matrix.arch}}.package VERSION=$VERSION
+
+      # - name: Build .rpm Package
+      #   if: ${{ matrix.os == 'linux' && matrix.rpm }}
+      #   run: |
+
+      #     VERSION=${{ needs.prepare.outputs.version }}
+      #     PCKG_PATH=usr/bin/pars
+
+      #     PACKAGE_OUTPUT_PATH_BASE=dist/$VERSION/${{matrix.os}}/pkg/deb/${{matrix.arch}}/$APPNAME
+      #     PACKAGE_BINARY_OUTPUT_PATH=$PACKAGE_OUTPUT_PATH_BASE/$PCKG_PATH
+
+      #     mkdir -p $PACKAGE_BINARY_OUTPUT_PATH
+
+      #     NEW_BASE_NAME=$APPNAME-${{matrix.os}}-${{matrix.arch}}$EXT
+      #     ORIGINAL_FILE_NAME="$APPNAME$EXT"
+
+      #     cp "$BINARY_OUTPUT_PATH_BASE/$ORIGINAL_FILE_NAME" "$PACKAGE_BINARY_OUTPUT_PATH"
+
+      #     make build.deb.package.${{matrix.arch}}.configuration VERSION=$VERSION
+      #     make build.deb.package.${{matrix.arch}}.payload VERSION=$VERSION
+      #     make build.deb.package.${{matrix.arch}}.package VERSION=$VERSION
