ek

diff --git a/.github/workflows/build-dev-matrix.yml b/.github/workflows/build-dev-matrix.yml
--- a/.github/workflows/build-dev-matrix.yml
+++ b/.github/workflows/build-dev-matrix.yml
@@ -56,6 +56,20 @@ jobs:
           echo "| Platform | Architecture | Type      | File Name | SHA-256 Checksum |" > $ARTIFACT_PATH/Checksums.md
           echo "|----------|--------------|-----------|-----------|------------------|" >> $ARTIFACT_PATH/Checksums.md
 
+      - name: Save files for later jobs
+        run: |
+          rm -rf /home/ahmetsoner/AS/prs/pars/temp/workflow
+          mkdir -p /home/ahmetsoner/AS/prs/pars/temp/workflow
+          cp -r ./* /home/ahmetsoner/AS/prs/pars/temp/workflow
+
+      # - name: Save files for later jobs
+      #   id: artifact
+      #   uses: actions/upload-artifact@v3
+      #   with:
+      #     name: build-artifacts
+      #     path: .
+      # path: ${{ steps.artifact.outputs.artifact_path }}
+
   build-matrix:
     runs-on: ubuntu-latest
     needs: prepare
@@ -69,8 +83,15 @@ jobs:
             targets: ["binary"]
             binary: true
             archive: tar.gz
-            # deb: true
-            # rpm: true
+            deb: false
+            rpm: true
+          # - os: linux
+          #   arch: arm64
+          #   targets: ["binary"]
+          #   binary: true
+          #   archive: tar.gz
+          #   deb: false
+          #   rpm: true
           # - os: windows
           #   arch: x86_64
           #   binary: true
@@ -96,10 +117,23 @@ jobs:
           #   package: deb
 
     steps:
-      - name: Checkout source code
-        uses: actions/checkout@v3
-        with:
-          fetch-depth: 0
+      # - name: Checkout source code
+      #   uses: actions/checkout@v3
+      #   with:
+      #     fetch-depth: 0
+
+      - name: Retrieve files from prepare job
+        run: |
+          cp -r /home/ahmetsoner/AS/prs/pars/temp/workflow/* ./
+
+          rm -rf build
+          VERSION=${{ needs.prepare.outputs.version }}
+          make build.cmake.$VERSION
+      # - name: Retrieve files from prepare job
+      #   uses: actions/download-artifact@v3
+      #   with:
+      #     name: build-artifacts
+      #     path: . # This means it downloads to the root of your working directory
 
       - name: print
         run: |
@@ -142,7 +176,7 @@ jobs:
 
           BINARY_OUTPUT_PATH_BASE=dist/$VERSION/${{matrix.os}}/bin/${{matrix.arch}}
           BINARY_OUTPUT_PATH=$BINARY_OUTPUT_PATH_BASE/$APPNAME$EXT
-          BINARY_CHCEKSUM_PATH=$BINARY_OUTPUT_PATH_BASE/checksum.txt
+          BINARY_CHECKSUM_PATH=$BINARY_OUTPUT_PATH_BASE/checksum.txt
 
           # Calculate the checksum and store it in a variable
           BINARY_CHECKSUM=$(sha256sum "$BINARY_OUTPUT_PATH" | awk '{print $1}')
@@ -155,7 +189,7 @@ jobs:
 
           echo "BINARY_OUTPUT_PATH_BASE=$BINARY_OUTPUT_PATH_BASE" >> $GITHUB_ENV
           echo "BINARY_OUTPUT_PATH=$BINARY_OUTPUT_PATH" >> $GITHUB_ENV
-          echo "BINARY_CHCEKSUM_PATH=$BINARY_CHCEKSUM_PATH" >> $GITHUB_ENV
+          echo "BINARY_CHECKSUM_PATH=$BINARY_CHECKSUM_PATH" >> $GITHUB_ENV
 
       - name: Create Artifact Binary
         if: matrix.binary
@@ -165,113 +199,223 @@ jobs:
           ORIGINAL_FILE_NAME="$APPNAME$EXT"
 
           # Copy the file to its new location with the new name
-          echo "-------"
-          echo $ARTIFACT_PATH
-          ls -la $ARTIFACT_PATH
-          echo "-------"
           cp "$BINARY_OUTPUT_PATH_BASE/$ORIGINAL_FILE_NAME" "$ARTIFACT_PATH/$NEW_BASE_NAME"
 
           CHECKSUM=$(cat "$BINARY_OUTPUT_PATH_BASE/checksum.txt")
           OS=${{matrix.os}}
           ARCH=${{matrix.arch}}
-          TYPE=Binary
+          TYPE="Binary"
           FILENAME=$NEW_BASE_NAME
 
           # Add entry to Checksums.md
           echo "| $OS | $ARCH | $TYPE | $FILENAME | $CHECKSUM |" >> "$ARTIFACT_PATH/Checksums.md"
 
-      # - name: Create Artifact Archive
-      #   if: ${{ matrix.binary && matrix.archive }}
-      #   run: |
-      #     VERSION=${{ needs.prepare.outputs.version }}
+      - name: Create Artifact Archive
+        if: ${{ matrix.binary && matrix.archive }}
+        run: |
+          VERSION=${{ needs.prepare.outputs.version }}
 
-      #     # Daha sonra burda file check yapılarak matrix.binary'den bağımsız ilerletilebilir olması sağlanacak
-      #     if [ -f "$BINARY_OUTPUT_PATH" ] && [ -f "$BINARY_CHECKSUM_PATH" ]; then
-      #         echo "Bin and Checksum files are present at specified paths."
-      #     else
-      #         echo "Required files do not exist. Skipping archive step."
-      #     fi
 
-      #     NEW_BASE_NAME=$APPNAME-${{matrix.os}}-${{matrix.arch}}.bin.${{ matrix.archive }}
-      #     BINARY_TEMP_PATH=dist/temp/$VERSION/$APPNAME-${{matrix.os}}-${{matrix.arch}}-${{ matrix.archive }}
+          if [ -f "$BINARY_OUTPUT_PATH" ] && [ -f "$BINARY_CHECKSUM_PATH" ]; then
+              echo "Bin and Checksum files are present at specified paths."
+          else
+              echo "Required files do not exist. Skipping archive step."
+          fi
 
-      #     mkdir -p $BINARY_TEMP_PATH/bin
-      #     cp $BINARY_OUTPUT_PATH "$BINARY_TEMP_PATH/bin/"
+          NEW_BASE_NAME=$APPNAME-${{matrix.os}}-${{matrix.arch}}.bin.${{ matrix.archive }}
+          BINARY_TEMP_PATH=dist/temp/$VERSION/$APPNAME-${{matrix.os}}-${{matrix.arch}}-${{ matrix.archive }}
 
-      #     mkdir -p $BINARY_TEMP_PATH/meta
-      #     cp $BINARY_OUTPUT_PATH_BASE/checksum.txt "$BINARY_TEMP_PATH/meta/checksum.txt"
+          mkdir -p $BINARY_TEMP_PATH/bin
+          cp $BINARY_OUTPUT_PATH "$BINARY_TEMP_PATH/bin/"
 
-      #     # Copy docs into the temp directory hierarchically
-      #     mkdir -p $BINARY_TEMP_PATH/docs
-      #     cp -r $HTML_OUTPUT_DIR/ $BINARY_TEMP_PATH/docs/
+          mkdir -p $BINARY_TEMP_PATH/meta
+          cp $BINARY_OUTPUT_PATH_BASE/checksum.txt "$BINARY_TEMP_PATH/meta/checksum.txt"
 
-      #     if [ "${{ matrix.archive }}" = "zip" ]; then
-      #       (cd $BINARY_TEMP_PATH && zip -r "$NEW_BASE_NAME" .)
-      #     elif [ "${{ matrix.archive }}" = "tar.gz" ]; then
-      #       (cd $BINARY_TEMP_PATH && tar -czf "$NEW_BASE_NAME" . --warning=no-file-changed || true )
-      #       if ! tar -tzf "$BINARY_TEMP_PATH/$NEW_BASE_NAME" > /dev/null; then
-      #         echo "Error with archive: Unable to list contents for validation."
-      #       fi
-      #     elif [ "${{ matrix.archive }}" = "7z" ]; then
-      #       (cd $BINARY_TEMP_PATH && 7z a "$NEW_BASE_NAME" *)
-      #     elif [ "${{ matrix.archive }}" = "rar" ]; then
-      #       ( cd $BINARY_TEMP_PATH && rar a $NEW_BASE_NAME * )
-      #     fi
+          # Copy docs into the temp directory hierarchically
+          mkdir -p $BINARY_TEMP_PATH/docs
+          cp -r $HTML_OUTPUT_DIR/ $BINARY_TEMP_PATH/docs/
 
-      #     cp "$BINARY_TEMP_PATH/$NEW_BASE_NAME" "$ARTIFACT_PATH/$NEW_BASE_NAME"
+          if [ "${{ matrix.archive }}" = "zip" ]; then
+            (cd $BINARY_TEMP_PATH && zip -r "$NEW_BASE_NAME" .)
+          elif [ "${{ matrix.archive }}" = "tar.gz" ]; then
+            (cd $BINARY_TEMP_PATH && tar -czf "$NEW_BASE_NAME" . --warning=no-file-changed || true )
+            if ! tar -tzf "$BINARY_TEMP_PATH/$NEW_BASE_NAME" > /dev/null; then
+              echo "Error with archive: Unable to list contents for validation."
+            fi
+          elif [ "${{ matrix.archive }}" = "7z" ]; then
+            (cd $BINARY_TEMP_PATH && 7z a "$NEW_BASE_NAME" *)
+          elif [ "${{ matrix.archive }}" = "rar" ]; then
+            ( cd $BINARY_TEMP_PATH && rar a $NEW_BASE_NAME * )
+          fi
 
-      #     # Calculate the checksum and store it in a variable
-      #     BINARY_PACKAGE_CHECKSUM=$(sha256sum "$BINARY_TEMP_PATH/$NEW_BASE_NAME" | awk '{print $1}')
+          cp "$BINARY_TEMP_PATH/$NEW_BASE_NAME" "$ARTIFACT_PATH/$NEW_BASE_NAME"
 
-      #     # Append the checksum and filepath to checksums.txt
-      #     echo "$BINARY_PACKAGE_CHECKSUM" > $BINARY_TEMP_PATH/checksum.txt
+          # Calculate the checksum and store it in a variable
+          BINARY_PACKAGE_CHECKSUM=$(sha256sum "$BINARY_TEMP_PATH/$NEW_BASE_NAME" | awk '{print $1}')
 
-      #     CHECKSUM=$(cat $BINARY_TEMP_PATH/checksum.txt)
-      #     OS=${{matrix.os}}
-      #     ARCH=${{matrix.arch}}
-      #     TYPE=Archieve
-      #     FILENAME=$NEW_BASE_NAME
+          # Append the checksum and filepath to checksums.txt
+          echo "$BINARY_PACKAGE_CHECKSUM" > $BINARY_TEMP_PATH/checksum.txt
 
-      #     echo "| $OS | $ARCH | $TYPE | $FILENAME | $CHECKSUM |" >> $ARTIFACT_PATH/Checksums.md
+          CHECKSUM=$(cat $BINARY_TEMP_PATH/checksum.txt)
+          OS=${{matrix.os}}
+          ARCH=${{matrix.arch}}
+          TYPE="Archieve"
+          FILENAME=$NEW_BASE_NAME
 
-      # - name: Build .deb Package
-      #   if: ${{ matrix.os == 'linux' && matrix.deb }}
-      #   run: |
+          echo "| $OS | $ARCH | $TYPE | $FILENAME | $CHECKSUM |" >> $ARTIFACT_PATH/Checksums.md
 
-      #     VERSION=${{ needs.prepare.outputs.version }}
-      #     PCKG_PATH=usr/bin/pars
+      - name: Build .deb Package
+        if: ${{ matrix.os == 'linux' && matrix.deb }}
+        run: |
 
-      #     PACKAGE_OUTPUT_PATH_BASE=dist/$VERSION/${{matrix.os}}/pkg/deb/${{matrix.arch}}/$APPNAME
-      #     PACKAGE_BINARY_OUTPUT_PATH=$PACKAGE_OUTPUT_PATH_BASE/$PCKG_PATH
+          VERSION=${{ needs.prepare.outputs.version }}
+          PCKG_PATH=usr/bin/pars
 
-      #     mkdir -p $PACKAGE_BINARY_OUTPUT_PATH
+          PACKAGE_OUTPUT_PATH_BASE=dist/$VERSION/${{matrix.os}}/pkg/deb/${{matrix.arch}}/$APPNAME
+          PACKAGE_BINARY_OUTPUT_PATH=$PACKAGE_OUTPUT_PATH_BASE/$PCKG_PATH
 
-      #     NEW_BASE_NAME=$APPNAME-${{matrix.os}}-${{matrix.arch}}$EXT
-      #     ORIGINAL_FILE_NAME="$APPNAME$EXT"
+          mkdir -p $PACKAGE_BINARY_OUTPUT_PATH
 
-      #     cp "$BINARY_OUTPUT_PATH_BASE/$ORIGINAL_FILE_NAME" "$PACKAGE_BINARY_OUTPUT_PATH"
+          NEW_BASE_NAME=$APPNAME-${{matrix.os}}-${{matrix.arch}}$EXT
+          ORIGINAL_FILE_NAME="$APPNAME$EXT"
 
-      #     make build.deb.package.${{matrix.arch}}.configuration VERSION=$VERSION
-      #     make build.deb.package.${{matrix.arch}}.payload VERSION=$VERSION
-      #     make build.deb.package.${{matrix.arch}}.package VERSION=$VERSION
+          cp "$BINARY_OUTPUT_PATH_BASE/$ORIGINAL_FILE_NAME" "$PACKAGE_BINARY_OUTPUT_PATH"
 
-      # - name: Build .rpm Package
-      #   if: ${{ matrix.os == 'linux' && matrix.rpm }}
-      #   run: |
+          make build.deb.package.${{matrix.arch}}.configuration VERSION=$VERSION
+          make build.deb.package.${{matrix.arch}}.payload VERSION=$VERSION
+          make build.deb.package.${{matrix.arch}}.package VERSION=$VERSION
 
-      #     VERSION=${{ needs.prepare.outputs.version }}
-      #     PCKG_PATH=usr/bin/pars
+      - name: Build .rpm Package
+        if: ${{ matrix.os == 'linux' && matrix.rpm }}
+        run: |
 
-      #     PACKAGE_OUTPUT_PATH_BASE=dist/$VERSION/${{matrix.os}}/pkg/deb/${{matrix.arch}}/$APPNAME
-      #     PACKAGE_BINARY_OUTPUT_PATH=$PACKAGE_OUTPUT_PATH_BASE/$PCKG_PATH
+          # if [ "${{ matrix.arch }}" = "x86" ]; then
+          #   # sudo dnf install glibc-devel.i686 libgcc.i686 gcc -y
+          #   export CC="gcc -m32"
+          #   export CGO_ENABLED=1
+          # elif [ "${{ matrix.arch }}" = "arm32" ]; then
+          #   # sudo dnf install gcc-arm-linux-gnueabihf binutils-arm-linux-gnueabihf -y
+          #   export CC="arm-linux-gnueabi-gcc"
+          # # elif [ "${{ matrix.arch }}" = "arm64" ]; then
+          # #   # sudo dnf install gcc-aarch64-linux-gnu binutils-aarch64-linux-gnu -y
+          # #   export CC=aarch64-linux-gnu-gcc
+          # #   export CXX=aarch64-linux-gnu-g++
+          # fi
 
-      #     mkdir -p $PACKAGE_BINARY_OUTPUT_PATH
 
-      #     NEW_BASE_NAME=$APPNAME-${{matrix.os}}-${{matrix.arch}}$EXT
-      #     ORIGINAL_FILE_NAME="$APPNAME$EXT"
+          VERSION=${{ needs.prepare.outputs.version }}
+          PCKG_PATH=usr/bin/pars
 
-      #     cp "$BINARY_OUTPUT_PATH_BASE/$ORIGINAL_FILE_NAME" "$PACKAGE_BINARY_OUTPUT_PATH"
+          PACKAGE_OUTPUT_PATH_BASE=dist/$VERSION/${{matrix.os}}/pkg/rpm/${{matrix.arch}}/$APPNAME
+          PACKAGE_BINARY_OUTPUT_PATH=$PACKAGE_OUTPUT_PATH_BASE/$PCKG_PATH
 
-      #     make build.deb.package.${{matrix.arch}}.configuration VERSION=$VERSION
-      #     make build.deb.package.${{matrix.arch}}.payload VERSION=$VERSION
-      #     make build.deb.package.${{matrix.arch}}.package VERSION=$VERSION
+          mkdir -p $PACKAGE_BINARY_OUTPUT_PATH
+
+          NEW_BASE_NAME=$APPNAME-${{matrix.os}}-${{matrix.arch}}$EXT
+          ORIGINAL_FILE_NAME="$APPNAME$EXT"
+
+          cp "$BINARY_OUTPUT_PATH_BASE/$ORIGINAL_FILE_NAME" "$PACKAGE_BINARY_OUTPUT_PATH"
+
+          make build.rpm.package.${{matrix.arch}}.configuration VERSION=$VERSION
+          make build.rpm.package.${{matrix.arch}}.payload VERSION=$VERSION
+          make build.rpm.package.${{matrix.arch}}.package VERSION=$VERSION
+
+          # Calculate RPM package checksum
+          RPM_OUTPUT_PATH_BASE=$PACKAGE_OUTPUT_PATH_BASE/RPMS/${{matrix.arch}}
+          RPM_CHECKSUM_PATH=$RPM_OUTPUT_PATH_BASE/checksum.txt
+
+          # RPM_OUTPUT_PATH=$PACKAGE_OUTPUT_PATH_BASE/RPMS/${{matrix.arch}}/$APPNAME-$VERION.fc41.${{matrix.arch}}.rpm
+          # Find the RPM file using wildcard and calculate the checksum
+          for file in $RPM_OUTPUT_PATH_BASE/$APPNAME*.${{matrix.arch}}.rpm; do
+            RPM_OUTPUT_PATH="$file"
+
+            # Calculate the checksum and store it in a variable
+            RPM_CHECKSUM=$(sha256sum "$RPM_OUTPUT_PATH" | awk '{print $1}')
+            echo "Checksum for $RPM_OUTPUT_PATH: $RPM_CHECKSUM"
+
+            # Append the checksum and filepath to checksums.txt
+            echo "$RPM_CHECKSUM" > "$RPM_CHECKSUM_PATH"
+
+            # Store paths and checksum in GitHub environment variables
+            echo "RPM_OUTPUT_PATH=$RPM_OUTPUT_PATH" >> $GITHUB_ENV
+          done
+
+          echo "RPM_OUTPUT_PATH_BASE=$RPM_OUTPUT_PATH_BASE" >> $GITHUB_ENV
+          echo "RPM_CHECKSUM_PATH=$RPM_CHECKSUM_PATH" >> $GITHUB_ENV
+
+
+
+
+          # Calculate SRPM package checksum
+          SRPM_OUTPUT_PATH_BASE=$PACKAGE_OUTPUT_PATH_BASE/SRPMS
+          SRPM_CHECKSUM_PATH=$SRPM_OUTPUT_PATH_BASE/checksum.txt
+
+          # Find the SRPM file using wildcard and calculate the checksum
+          for file in $SRPM_OUTPUT_PATH_BASE/$APPNAME*.src.rpm; do
+            SRPM_OUTPUT_PATH="$file"
+
+            # Calculate the checksum and store it in a variable
+            SRPM_CHECKSUM=$(sha256sum "$SRPM_OUTPUT_PATH" | awk '{print $1}')
+            echo "Checksum for $SRPM_OUTPUT_PATH: $SRPM_CHECKSUM"
+
+            # Append the checksum and filepath to checksums.txt
+            echo "$SRPM_CHECKSUM" > "$SRPM_CHECKSUM_PATH"
+
+            # Store paths and checksum in GitHub environment variables
+            echo "SRPM_OUTPUT_PATH=$SRPM_OUTPUT_PATH" >> $GITHUB_ENV
+          done
+
+          echo "SRPM_OUTPUT_PATH_BASE=$SRPM_OUTPUT_PATH_BASE" >> $GITHUB_ENV
+          echo "SRPM_CHECKSUM_PATH=$SRPM_CHECKSUM_PATH" >> $GITHUB_ENV
+
+      - name: Create Artifact RPM
+        if: ${{ matrix.os == 'linux' && matrix.rpm }}
+        run: |
+
+          NEW_BASE_NAME=$APPNAME-${{matrix.os}}-${{matrix.arch}}.rpm
+          ORIGINAL_FILE_NAME="$APPNAME$EXT"
+
+          # Copy the file to its new location with the new name
+
+          for file in $RPM_OUTPUT_PATH_BASE/$APPNAME*.${{matrix.arch}}.rpm; do
+            RPM_OUTPUT_PATH="$file"
+
+            cp "$RPM_OUTPUT_PATH" "$ARTIFACT_PATH/$NEW_BASE_NAME"
+          done
+
+          CHECKSUM=$(cat "$RPM_OUTPUT_PATH_BASE/checksum.txt")
+          OS=${{matrix.os}}
+          ARCH=${{matrix.arch}}
+          TYPE="RPM"
+          FILENAME=$NEW_BASE_NAME
+
+          # Add entry to Checksums.md
+          echo "| $OS | $ARCH | $TYPE | $FILENAME | $CHECKSUM |" >> "$ARTIFACT_PATH/Checksums.md"
+
+
+
+
+          SNEW_BASE_NAME=$APPNAME-${{matrix.os}}-${{matrix.arch}}.src.rpm
+          ORIGINAL_FILE_NAME="$APPNAME$EXT"
+
+          # Copy the file to its new location with the new name
+
+          for file in $SRPM_OUTPUT_PATH_BASE/$APPNAME*.src.rpm; do
+            SRPM_OUTPUT_PATH="$file"
+
+            cp "$SRPM_OUTPUT_PATH" "$ARTIFACT_PATH/$SNEW_BASE_NAME"
+          done
+
+          CHECKSUM=$(cat "$SRPM_OUTPUT_PATH_BASE/checksum.txt")
+          OS=${{matrix.os}}
+          ARCH=${{matrix.arch}}
+          TYPE="RPM (Source)"
+          FILENAME=$SNEW_BASE_NAME
+
+          # Add entry to Checksums.md
+          echo "| $OS | $ARCH | $TYPE | $FILENAME | $CHECKSUM |" >> "$ARTIFACT_PATH/Checksums.md"
+      - name: Save files for later jobs
+        run: |
+          rm -rf /home/ahmetsoner/AS/prs/pars/temp/workflow
+          mkdir -p /home/ahmetsoner/AS/prs/pars/temp/workflow
+          cp -r ./* /home/ahmetsoner/AS/prs/pars/temp/workflow
